version: '3'
networks:
  netOSM:
    external:
       name: ${OSM_NETWORK:-netosm}
services:
  grafana:
    image: grafana/grafana
    volumes:
      - ./dashboards-osm.yml:/etc/grafana/provisioning/dashboards/dashboards-osm.yml
      - ./osm-sample-dashboard.json:/etc/grafana/provisioning/dashboards/osm-sample-dashboard.json
      - ./datasource-prometheus.yml:/etc/grafana/provisioning/datasources/datasource-prometheus.yml
    hostname: grafana
    ports:
      - "${OSM_PM_PORTS:-3000:3000}"
    networks:
      - netOSM
