# -*- coding: utf-8 -*-

# Copyright 2020 Arctos Labs Scandinavia AB
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.
# See the License for the specific language governing permissions and
# limitations under the License.

options:
  image:
    description: Docker image name
    type: string
    default: opensourcemano/pla:8.0.0rc1
  port:
    description: Port number
    type: int
    default: 8080 # Fake port
  kafka_host:
    description: Kafka Hostname
    type: string
    default: kafka-k8s
  kafka_port:
    description: Kafka Port
    type: int
    default: 9092
  mongo_uri:
    description: Mongo URI
    type: string
    default: mongodb://mongodb-k8s:27017
  log_level:
    description: Log level
    type: string
    default: INFO
