# Copyright 2019 TATA ELXSI
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.
# See the License for the specific language governing permissions and
# limitations under the License
# Author: Vijay Nag B S (vijaynag.bs@tataelxsi.co.in)

apiVersion: v1
kind: Service
metadata:
  name: nbi
spec:
  ports:
  - nodePort: 9999
    port: 9999
    protocol: TCP
    targetPort: 9999
  selector:
    app: nbi
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nbi
  labels:
    app: nbi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nbi
  template:
    metadata:
      labels:
        app: nbi
    spec:
      initContainers:
      - name: kafka-mongo-test
        image: alpine:latest
        command: ["sh", "-c", "until (nc -zvw1 kafka 9092 && nc -zvw1 mongo 27017); do sleep 3; done; exit 0"]
      containers:
      - name: nbi
        image: opensourcemano/nbi:8
        ports:
        - containerPort: 9999
          protocol: TCP
        env:
         - name: OSMNBI_DATABASE_HOST
           value: mongo
         - name:  OSMNBI_MESSAGE_HOST
           value: kafka
        envFrom:
        - secretRef:
           name: nbi-secret
        volumeMounts:
         - name: osm-packages
           mountPath: /app/storage
      volumes:
       - name: osm-packages
         hostPath:
          path: /var/lib/osm/osm_osm_packages/_data
