# Copyright 2019 TATA ELXSI
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.
# See the License for the specific language governing permissions and
# limitations under the License
# Author: Vijay Nag B S (vijaynag.bs@tataelxsi.co.in)

apiVersion: v1
kind: Service
metadata:
  name: ro
spec:
  clusterIP: None
  ports:
  - port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: ro
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ro
  labels:
    app: ro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ro
  template:
    metadata:
      labels:
        app: ro
    spec:
      initContainers:
      - name: ro-db-test
        image: alpine:latest
        command: ["sh", "-c", "until nc -zvw1 mysql 3306; do  sleep 3 ; done; exit 0"]
      containers:
      - name: ro
        image: opensourcemano/ro:7
        ports:
        - containerPort: 9090
          protocol: TCP
        env:
         - name: RO_DB_HOST
           value: mysql
        envFrom:
        - secretRef:
           name: ro-secret
        volumeMounts:
         - name: ro
           mountPath: /var/log/osm
      volumes:
      - name: ro
        hostPath:
         path: /var/lib/osm/osm_ro/_data
